version: "3"

services:
  botlg:
    container_name: botlg
    image: node:botlg
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./app/:/app/"
    ports:
      - ${BOTLG_PORT}:80

  php_api:
    container_name: php_api
    image: php:php_api
    build:
      context: ./
      dockerfile: ./php-api.Dockerfile
    volumes:
      - "./php-api/:/var/www/html/"
    ports:
      - ${PHPAPI_PORT}:80

  postgres_botlg:
    container_name: postgres_botlg
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./init-postgres/:/docker-entrypoint-initdb.d/"
