version: "3"

services:
  bot-lg:
    container_name: bot-lg
    image: node:bot-lg
    build:
      context: ./
      dockerfile: ./bot-lg.Dockerfile
    volumes:
      - "./app/:/app/"
    ports:
      - ${BOTLG_PORT}:80
    
  php-api:
    container_name: php-api
    image: php:php-api
    build:
      context: ./
      dockerfile: ./php-api.Dockerfile
    volumes:
      - "./php-api/:/var/www/html/"  
    ports:
      - ${PHPAPI_PORT}:80
    
  postgres-bot-lg:
    container_name: postgres-bot-lg
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./init-postgres/:/docker-entrypoint-initdb.d/"
    ports:
      - ${POSTGRES_PORT}:5432
