version: "3"

services:
  botlg:
    container_name: botlg
    image: node:botlg
    build:
      context: ./docker/
      dockerfile: Dockerfile
    volumes:
      - "./app/:/app/"

  mongodb:
    container_name: mongodb
    image: ${IMAGE_MONGODB}
    env_file:
      - ./docker/mongodb.env
    volumes:
      - ${DATA_PATH}/mongodb/:/var/lib/mongodb/

  web:
    container_name: web
    image: ${IMAGE_HTTPD}
    volumes:
      - ./mkdocs/build/en/:/usr/local/apache2/htdocs/en/
      - ./mkdocs/build/fr/:/usr/local/apache2/htdocs/fr/
    ports:
      - 80:80
